[build]
  cmd = "go build -o ./tmp/main ./cmd/spotifind"
  bin = "./tmp/main"
  full_bin = "./tmp/main"
  include_ext = ["go", "toml"]
  exclude_dir = ["tmp", "bin"]
  delay = 1000

[log]
  time = false

[color]
  build = "yellow"
  runner = "green"
